# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\defaultuser0\Downloads\Reprise_POO\Reprise_POO\Pharmacie\Pharmacie\UI\dialog_patient.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_patient(object):
    def setupUi(self, Dialog_patient):
        Dialog_patient.setObjectName("Dialog_patient")
        Dialog_patient.resize(525, 369)
        self.label = QtWidgets.QLabel(Dialog_patient)
        self.label.setGeometry(QtCore.QRect(50, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog_patient)
        self.pushButton.setGeometry(QtCore.QRect(200, 200, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog_patient)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 250, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog_patient)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog_patient)
        QtCore.QMetaObject.connectSlotsByName(Dialog_patient)

    def retranslateUi(self, Dialog_patient):
        _translate = QtCore.QCoreApplication.translate
        Dialog_patient.setWindowTitle(_translate("Dialog_patient", "Dialog_patient"))
        self.label.setText(_translate("Dialog_patient", "Numéro du patient"))
        self.pushButton.setText(_translate("Dialog_patient", "Ajouter Patient"))
        self.pushButton_2.setText(_translate("Dialog_patient", "Modifier Patient"))
        self.pushButton_3.setText(_translate("Dialog_patient", "Supprimer Patient"))
